services:
  top.api:
    image: ghcr.io/alexasky/top-app-api/top-app-api:develop
    container_name: top-api
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./.env:/opt/app/.env
