name: Publish Docker

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGO_LOGIN: ${{ secrets.MONGO_LOGIN }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      MONGO_HOST: ${{ secrets.MONGO_HOST }}
      MONGO_PORT: ${{ secrets.MONGO_PORT }}
      MONGO_AUTHDATABASE: ${{ secrets.MONGO_AUTHDATABASE }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build \
            --build-arg MONGO_LOGIN=${MONGO_LOGIN} \
            --build-arg MONGO_PASSWORD=${MONGO_PASSWORD} \
            --build-arg MONGO_HOST=${MONGO_HOST} \
            --build-arg MONGO_PORT=${MONGO_PORT} \
            --build-arg MONGO_AUTHDATABASE=${MONGO_AUTHDATABASE} \
            --build-arg JWT_SECRET=${JWT_SECRET} \
            -t ghcr.io/alexasky/top-app-api:develop .

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: ghcr.io
          name: alexasky/top-app-api
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: develop
